server:
  port: 8000

spring:
  application:
    name: dist-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  shardingsphere:
    ## 是否开启SQL显示
    props:
      sql:
        show: true
    datasource:
      # 数据库
      names: dist-user-01,dist-user-02,dist-user-03
      # 个人活期库
      dist-user-01:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.56.10:3306/dist-user-01?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
      # 个人定期库
      dist-user-02:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.56.10:3306/dist-user-02?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
      # 对公户库
      dist-user-03:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.56.10:3306/dist-user-03?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    sharding:
      # 分库策略 => 根据type拆分到不同的库中
      default-database-strategy:
        inline:
          sharding-column: type
          algorithm-expression: dist-user-$->{type}
      # 配置分表的规则
      tables:
        # 逻辑表名
        tb_user:
          # 数据节点：数据源$->{0..N}.逻辑表名$->{0..N}
          actual-data-nodes: dist-user-0$->{1..3}.tb_user$->{2020..2022}
          # 分表策略 => 根据year拆分到不同的表中
          table-strategy:
            inline:
              sharding-column: year
              algorithm-expression: tb_user$->{year}


mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml